#!/bin/perl -W
# Filter Hiawatha access.log file, according:
#  1. Certain IP's
#  2. not found errors + redirects etc.
#  3. bots
#
# Elmar Klausmeier, 29-Nov-2021
# Elmar Klausmeier, 04-Dec-2021: added crawlers, no longer split $F[6] at '-'
# Elmar Klausmeier, 10-Dec-2021: added IPs for robots.txt reader, added getopt + statistics
# Elmar Klausmeier, 23-May-2022: Class C network filtering
# Elmar Klausmeier, 29-May-2023: add bad referer

use strict;

use Getopt::Std;
my %opts = ();
getopts('o:',\%opts);
my $statout = (defined($opts{'o'}) ? $opts{'o'} : undef);
my ($emptyUA,$badURL,$badReferer,$smallUA) = (0,0,0,0);


my %classC = (
	'5.188.210' => 0,	# DogHostNetwork in Russia
	'45.86.200' => 0,
	'45.128.199' => 0,	# PANQ in Netheland
	'64.124.8' => 0,	# Zayo
	'74.80.208' => 0,	# Castle Global @ thehive.ai
	'85.203.21' => 0,	# VPN Consumer Network Singapore
	'185.82.72' => 0,	# NL Layerswitch
	'192.168.0' => 0,	# local network
	'192.168.178' => 0,	# local network
	'185.82.72.200' => 0	# NL Layerswitch
);
my %ips = (
	'2.57.122.98' => 0,	# PPTechnology.cc
	'3.84.244.156' => 0, '3.94.81.106' => 0, '3.219.212.117' => 0, '18.212.118.57' => 0, '18.232.89.176' => 0,
	'34.239.184.105' => 0, '44.200.160.109' => 0, '54.80.126.99' => 0, '54.162.60.209' => 0,
	'54.164.82.20' => 0, '54.175.209.89' => 0, '54.196.194.235' => 0, '54.197.65.200' => 0,
	'54.211.110.230' => 0, '54.221.123.72' => 0, '54.226.71.23' => 0, '54.226.76.89' => 0,	# compute-1.amazonaws.com
	'37.20.208.218' => 0,	# Siberia rt.ru
	'46.4.62.166' => 0,	# Hetzner
	'45.8.17.18' => 0, '45.8.17.19' => 0, '45.8.17.23' => 0, '45.8.17.35' => 0,	# TnR Technologies in Netherland
	'45.61.187.81' => 0,	# FranTech
	'45.146.164.110' => 0, '45.146.165.37' => 0,
	'45.155.204.146' => 0,	# hostway.ru Russia
	'60.217.75.69' => 0, '61.147.15.67' => 0,	# China
	'62.138.2.14' => 0, '62.138.2.214' => 0, '62.138.2.160' => 0,
	'62.138.3.52' => 0, '62.138.6.15' => 0, '85.25.210.23' => 0, '92.204.54.123' => 0,	# startdedicated.de
	'62.210.127.188' => 0,	# poneytelecom.eu
	'66.240.192.138' => 0, '66.240.219.133' => 0, '66.240.219.146' => 0, '66.240.236.119' => 0,
	'71.6.135.131' => 0, '71.6.146.130' => 0, '71.6.146.185' => 0, '71.6.158.166' => 0,
	'71.6.165.200' => 0, '71.6.167.142' => 0, '71.6.199.23' => 0, '80.82.77.33' => 0,
	'80.82.77.139' => 0, '82.221.105.6' => 0, '82.221.105.7' => 0,	# shodan.io
	'85.203.21.67' => 0,	# VPN consumer network Singapore
	'71.6.232.4' => 0,	# quadmetrics.com
	'84.244.19.15' => 0, '84.244.23.8' => 0, '84.244.32.151' => 0,	# irknet.ru
	'91.240.118.252' => 0,	# changway.hk
	'94.232.45.12' => 0,	# Dmitriy Panchenko
	'103.50.168.236' => 0,	# goalbd.net
	'109.102.111.20' => 0,	# Telekom_Romania
	'127.0.0.1' => 0,	# localhost
	'128.14.134.170' => 0, '193.118.53.194' => 0,	# Zenlayer.com
	'138.246.253.24' => 0, '106.55.250.60' => 0,	# various robots.txt reader
	'145.239.154.82' => 0, '145.239.154.84' => 0, '145.239.154.85' => 0,	# OVH France
	'152.89.196.62' => 0, '152.89.196.211' => 0,	# Russian Starcrecium
	'158.69.195.206' => 0,	# OVH Montreal
	'178.158.11.102' => 0, '178.158.65.110' => 0,	# mageal.ru
	'180.112.224.7' => 0,	# Chinanet Jiangsu Province Network
	'183.136.225.32' => 0, '183.136.225.35' => 0,	# China Leon Ship Network
	'185.7.214.104' => 0,	# Hong Kong
	'193.106.29.210' => 0,	# Ukraine Infiumhost.com
	'193.106.191.48' => 0,	# Russian Kanzas LLC
	'195.54.160.149' => 0,	# laincou.name
	'213.226.123.186' => 0	# Novoselov Saint Petersburg
);
my %errorCode = ( 301 => 0, 302 => 0, 303 => 0, 400 => 0, 403 => 0, 404 => 0, 405 => 0, 500 => 0, 501 => 0, 503 => 0, 505 => 0 );
my %bots = (
	'{jndi' => 0,
	'360spider' => 0, adsbot => 0, 'adsbot.html' => 0, adscanner => 0, ahrefsbot => 0, ahrefssiteaudit => 0,
	aiohttp => 0, amazonbot => 0,
	'appengine-google' => 0, applebot => 0, 'archive.org_bot' => 0, awariosmartbot => 0,
	baiduspider => 0, 'baiduspider-render' => 0, barkrowler => 0, bingbot => 0, bingpreview => 0,
	blexbot => 0, bytespider => 0,
	ccbot => 0, censysinspect => 0, 'chrome-lighthouse' => 0,
	'clark-crawler2' => 0, 'coccocbot-image' => 0, 'coccocbot-web' => 0, coibotparser => 0,
	crawler => 0, crawler2 => 0, 'crawler.php' => 0,
	criteobot => 0, curl => 0,
	dareboost => 0, dataforseobot => 0, detection => 0, 'dingtalkbot-linkservice' => 0,
	discordbot => 0, dotbot => 0,
	duckduckbot => 0, 'duckduckgo-favicons-bot' => 0,
	entferbot => 0, expanse => 0,
	facebookexternalhit => 0, 'feedsearch-crawler' => 0, 'flat-crawler' => 0, fluid => 0,
	'gdnplus.com' => 0, gnu => 0, 'go-http-client' => 0,
	googlebot => 0, 'googlebot-image' => 0,
	hello => 0,
	infotigerbot => 0, internetmeasurement => 0, ioncrawl => 0,
	l9explore => 0, l9tcpid => 0, 'libwww-perl' => 0, lighthouse => 0, 'linespider' => 0,
	linkdexbot => 0, linkedinbot => 0, 'linkfluence.com' => 0, livelapbot => 0, ltx71 => 0,
	masscan => 0, 'masscan-ng' => 0, mediapartners => 0, 'mediapartners-google' => 0,
	megaindex => 0, mindupbot => 0, mj12bot => 0, modabot => 0, mojeekbot => 0, mozilliqa => 0, mrgbot => 0,
	netcraft => 0, netcraftsurveyagent => 0, netestate => 0, netpeakcheckerbot => 0,
	'netsystemsresearch.com' => 0,
	neevabot => 0, nicecrawler => 0, ninjbot => 0, 'node-fetch' => 0, nuclei => 0,
	onalyticabot => 0,
	petalbot => 0, phxbot => 0, pingdompagespeed => 0, pinterestbot => 0, 'project-resonance' => 0,
	proximic => 0, 'pulsepoint-ads.txt-crawler' => 0, 'python-requests' => 0,
	sabsimbot => 0, scaninfo => 0, screaming => 0, seekportbot => 0, semanticbot => 0,
	semrushbot => 0, 'semrushbot-ba' => 0, seocompany => 0, seolyt => 0,
	serendeputybot => 0, seznambot => 0, sitecheckerbotcrawler => 0,
	sitelockspider => 0, sitesucker => 0,
	slackbot => 0, 'slack-imgproxy' => 0, smtbot => 0, surdotlybot => 0,
	tchelebi => 0, trendsmapresolver => 0, tweetmemebot => 0, twingly => 0, twitterbot => 0,
	ucrawl => 0,
	virustotal => 0, 'web-crawler' => 0, 'webmeup-crawler' => 0,
	webprosbot => 0, 'webpros.com' => 0, woorankreview => 0,
	'x-fb-crawlerbot' => 0, xfa1 => 0, yacybot => 0,
	yandexbot => 0, yandexfavicons => 0, yandeximageresizer => 0, yandeximages => 0, yandexmetrika => 0,
	yandexnews => 0, yandexrenderresourcesbot => 0, youbot => 0,
	zgrab => 0,
);

# Hiawatha log format:
#   1. host
#   2. date
#   3. code
#   4. size
#   5. URL
#   6. referer
#   7. user agent

W: while (<>) {
	my @F = split /\|/;
	next if ($#F <= 3);
	my $ip24 = substr($F[0],0,rindex($F[0],'.'));
	if (defined($classC{$ip24})) { $classC{$ip24} += 1; next; }
	if (defined($ips{$F[0]})) { $ips{$F[0]} += 1; next; }
	if ($#F <= 5) { $emptyUA += 1; next; }
	if (defined($errorCode{$F[2]})) { $errorCode{$F[2]} += 1; next; }	# not found errors are ignored
	if ($F[4] =~ /XDEBUG_SESSION_START|HelloThink(CMF|PHP|PHP21)/) { $badURL += 1; next; }
	if ($F[5] =~ /XDEBUG_SESSION_START|HelloThink(CMF|PHP|PHP21)/) { $badReferer += 1; next; }
	if ($#F >= 6) {	# Is UA field available?
		if (length($F[6]) <= 3) { $smallUA += 1; next W; }
		for ( split(/[ :;,\/\(\)\@\$]/,lc $F[6]) ) {
			if (defined($bots{$_})) { $bots{$_} += 1; next W; } 	# skip bots
		} 
	} 
	print;
}

if (defined($statout)) {
	open(F,">$statout") || die("Cannot write to $statout");
	for (sort keys %classC) {
		next if ($classC{$_} == 0);
		printf(F "ClassC\t%d\t%s\n",$classC{$_},$_);
	}
	for (sort keys %ips) {
		next if ($ips{$_} == 0);
		printf(F "IP\t%d\t%s\n",$ips{$_},$_);
	}
	printf(F "eUA\t%d\n",$emptyUA);
	printf(F "badURL\t%d\n",$badURL);
	printf(F "badReferer\t%d\n",$badReferer);
	for (sort keys %errorCode) {
		next if ($errorCode{$_} == 0);
		printf(F "code\t%d\t%d\n",$errorCode{$_},$_);
	}
	printf(F "sUA\t%d\n",$smallUA);
	for (sort keys %bots) {
		next if ($bots{$_} == 0);
		printf(F "bot\t%d\t%s\n",$bots{$_},$_);
	}
}

