#!/bin/perl -W
# Count number of times a URL was hit. Input is Hiawatha-like access log file.
# NGINX access log file works as well, just change log-format.
# Show tabular results using Datatables JavaScript, show bar charts via Apache ECharts.
#
# Hiawatha log format:
#   1. host
#   2. date
#   3. code
#   4. size
#   5. URL
#   6. referer
#   7. user agent
#
# Elmar Klausmeier, 04-Dec-2021
# Elmar Klausmeier, 11-Jan-2022: Aggregated values, new sub cntInH
# Elmar Klausmeier, 29-Mar-2022: Tooltips in ECharts, factored out JS to reduce size
# Elmar Klausmeier, 25-Aug-2022: Filter illegal HTML chars
# Elmar Klausmeier, 03-Dec-2022: Filter \r from URL
# Elmar Klausmeier, 24-Oct-2023: Aggregate according protocol
# Elmar Klausmeier, 27-Jun-2024: Limit output to entries with at least m visits
# Elmar Klausmeier, 28-Oct-2024: Added function fmt1000

use strict;
use Time::Local;
use POSIX qw(strftime);
use Getopt::Std;

my %opts = ('m' => 0);
getopts('m:',\%opts);
my $minVisit = defined($opts{'m'}) ? $opts{'m'} : 1;

my $nx = 0;	# number of entries in ecoption[] array
my %monthNum = (
	'Jan' => 1, 'Feb' => 2, 'Mar' => 3, 'Apr' => 4,
	'May' => 5, 'Jun' => 6, 'Jul' => 7, 'Aug' => 8,
	'Sep' => 9, 'Oct' => 10, 'Nov' => 11, 'Dec' => 12
);
my %H;	# hash: method+URL+protocol is key
my %hist;	# histogram: year+week is key, currently not used
my $dt = strftime("%F %T",localtime());	# only for printing


print << "EOF";
<!doctype html>
<html>
	<title>URL Count</title>
	<link href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABbklEQVQ4T2OUn/2+loGRoZqR4T87AwngPwPjT4b/DK2M8nPe/yBVM8wekCGMCnPe/SfBYgylKAYk67AzMCEp2ff4N4O+KAvDtz//GXY8+M1gKcnCoCHEzDD/6k+4KhQD7iQKMDAyMjD8h7qp6OBXhgx9DoZX3/4zJOz8wrDMk4eBn52RwXvDZ9wGgExvPfUdrmBbIC/YgKojXxkOhvEzzLz0g6Hn7A/SDPj48z/Dz7//GcwlWBmc1nxkeP4VEWwYXgB6l+EnkJh75QfDpAs/GUAu0BRiYfgH9FfZoa8Ma+/8RglIDAMuvfnLcPTZb4aTz/8wHHn2B8WAEqAB6wkZgC0MQF74/ZeBwUSChcFp9UeGF8AwgQEMF+AKxNpjXxn2h/AzTAcGYi++QMQXjSu8eBh42fBEY7ouOzgdwMDeR78ZDKAJaev93wzWUiwMWsCENPsKjoRETpKmPDOBsjPQ2dXABExSdmYA5kRg0mgFAI5W3Y01yGITAAAAAElFTkSuQmCC" rel="icon" type="image/x-icon">

	<link href="https://cdn.datatables.net/3.0.4/css/dataTables.dataTables.min.css" rel=stylesheet />
	<style>
		.histogram { height:400px; width:400px; }
	</style>
<body>
<h1>URL Count $dt &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (<a href=/statcnt.html>uncount</a>)</h1>
<table id="urlcnt" class="display"></table>
<table><thead><tr><th>Year<th>Month<th>Week
	<tbody><tr>
	<td><div class="histogram" id="containerYear"></div>
	<td><div class="histogram" id="containerYearMonth"></div>
	<td><div class="histogram" id="containerYearWeek"></div>
</table>
</body>

<!-- Datatables -->
<script type="text/javascript" src="https://cdn.datatables.net/3.0.4/js/dataTables.min.js"></script>

<!-- Apache ECharts -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>

<script type="text/javascript">
function d(i) {	// we keep this function name short as it is used thousands of times in HTML table
	let i3 = 3 * i;
	for (k=0; k<3; ++k) {
		j = i3 + k;
		if (ecoption[j] && typeof ecoption[j] === 'object') {
			ecoption[j].yAxis = {type:'value'};
			ecoption[j].tooltip = { trigger:'axis', axisPointer:{type:'shadow'} };
			myChart[k].setOption(ecoption[j]);
		} else break;
	}
	return false;	// see: https://stackoverflow.com/questions/1070760/javascript-function-in-href-vs-onclick
}

let ecoption = [];
/*
{	// year
	xAxis: { type: 'category', data: [] },
	yAxis: { type: 'value' },
	series: [ { data: [], type: 'bar' } ]
},
{	// year/month
	xAxis: { type: 'category', data: [] },
	yAxis: { type: 'value' },
	series: [ { data: [], type: 'bar' } ]
},
{	// year/week
	xAxis: { type: 'category', data: [] },
	yAxis: { type: 'value' },
	series: [ { data: [], type: 'bar' } ]
}];
*/

var urlFrequency = [
EOF

# Count in hash H
sub cntInH(@) {
	my ($size,$url,$year,$yearmonth,$yearweek) = ($_[0],$_[1],$_[2],$_[3],$_[4]);

	my $p = \$H{$url};
	if (defined($$p)) {
		$$p->[0] += 1;
		$$p->[1] += $size;
		# $$p->[2]{$year} += 1;
		# $$p->[3]{$yearmonth} += 1;
		# $$p->[4]{$yearweek} += 1;
		my $q = $$p->[2];
		if ($q->[$#{$q}][0] eq $year) { $q->[$#{$q}][1] += 1; }
		else { push $q->@*,[$year,1]; }
		$q = $$p->[3];
		if ($q->[$#{$q}][0] eq $yearmonth) { $q->[$#{$q}][1] += 1; }
		else { push $q->@*,[$yearmonth,1]; }
		$q = $$p->[4];
		if ($q->[$#{$q}][0] eq $yearweek) { $q->[$#{$q}][1] += 1; }
		else { push $q->@*,[$yearweek,1]; }
	} else {
		# $H{$F[4]} = [ 1, $F[3], {$year=>1}, {$yearmonth=>1}, {$yearweek=>1} ];
		$H{$url} = [ 1, $size, [[$year,1]], [[$yearmonth,1]], [[$yearweek,1]], $nx++ ];
	}
}

sub fmt1000(@) {	# thousand's formating
	# Perl printf to use commas as thousands-separator:
	# stackoverflow.com/questions/33442240 + perlmonks.org?node_id=1035411
	return scalar reverse(join(',', (unpack('(A3)*',reverse $_[0]))));
}


while (<>) {
	my @F = split /\|/;
	next if ($#F < 5);	# need URL at least, assert that referer is also there
	next if ($F[2] =~ /(4|5)\d\d/);	# these records cannot be processed
	$F[4] =~ s/\r//g;	# strip \r
	# Original Hiawatha log-format: my ($wday,$day,$monthName,$year,$hms,$dl) = split(/ /,$F[1]);
	my ($day,$monthName,$year,$hour,$minute,$second,$dl) = split(/:|\/| /,$F[1]);
	my $month = $monthNum{$monthName};
	my $epoch = timelocal( 0, 0, 0, $day, $month-1, $year-1900 );
	my $week  = strftime("%U",localtime($epoch));
	my ($yearweek,$yearmonth) = ("$year/$week","$year/$month");
	$hist{$yearweek} += 1;	# not used
	# Special handling for Elmar Klausmeier's blog
	$F[4] =~ s/^GET \/(aux|blog|jpilot|music|gallery|lemire|koehntopp|mobility|myrawest|paternoster|panorama|nukeklaus|saaze-example|wendt)(.*)\/ /GET \/$1$2 /;	# drop trailing slash in /blogXXX/ or /musicXXX/, etc.
	cntInH($F[3],$F[4],$year,$yearmonth,$yearweek);
	my ($aggrF4prt,$aggrF4mthp) = ($F[4],$F[4]);
	$aggrF4prt =~ s/^(\w+) ([^ ]+) (\w+)\/([\.\-\w]+)/$1 $2 aPrt/;	# aggregate according protocol only
	cntInH($F[3],$aggrF4prt,$year,$yearmonth,$yearweek);
	$aggrF4mthp =~ s/^(\w+) \/([^\/]+)([^ ]*) (\w+)\/([\.\-\w]+)/aMth $2 aPrt/;	# aggregate according method+protocol
	cntInH($F[3],$aggrF4mthp,$year,$yearmonth,$yearweek);
}

for my $f4 (keys %H) {
	next if ($H{$f4}[0] < $minVisit);
	my ($meth,$url,$prot) = split(/ /,$f4);
	$meth = 'unknown' if (!defined($meth));
	$meth = 'unknown' if ($meth !~ /\w+/);	# cope for stuff like '\x16\x03\x01\x00u\x01...'
	$url = 'unknown' if (!defined($url));
	$prot = 'unknown' if (!defined($prot));
	$url =~ s/'/&#39;/g;
	$url =~ s/"/&#34;/g;
	$url =~ s/:/&#58;/g;
	$url =~ s/</&#3c;/g;
	$url =~ s/>/&#3e;/g;
	$url =~ s/\\/&#92;/g;
	$url =~ s/\?/&#63;/g;
	my $displayURL = (length($url) > 95) ? substr($url,0,90).'...'.substr($url,-5) : $url;
	my $size = fmt1000( $H{$f4}[1] );
	printf("\t['<a href=\"#\" onclick=\"return d(%d);\">%s</a>','%s','%s','%s','<a href=\\\".%s\\\">%s</a>'],\n",
		$H{$f4}[5],fmt1000($H{$f4}[0]),$size,$meth,$prot,$url,$displayURL);
}
printf("];\n\n");

#my $pH = \$H{'GET /blog/ HTTP/1.1'};
#printf("// length=%d, |%s|\n",$#{$$pH},$$pH->[2][0][0]);
for my $f4 (keys %H) {
	next if ($H{$f4}[0] < $minVisit);
	my $pH = \$H{$f4};
	my $i3 = 3 * $$pH->[5];
	for (my $j=0; $j<3; ++$j) {
		printf("ecoption[%d] = {\n"
		."	xAxis:{type:'category', data:[",$i3+$j);
		#printf("ecoption[%d].xAxis.data = [",$j);
		for (@{$$pH->[2+$j]}) {	# x-values
			printf("'%s',",$_->[0]);	# luckily JS allows dangling commas
		}
		#printf(" ];\n");
		#printf("ecoption[%d].series[0].data = [",$j);
		#."	yAxis: {type:'value'},\n"
		printf("]},\n"
		."	series: [{data:[");
		for (@{$$pH->[2+$j]}) {	# y-values
			printf("'%s',",$_->[1]);	# luckily JS allows dangling commas
		}
		printf("], type:'bar'}]\n};\n");
		#printf(" ];\n");
	}
}

print << "EOF";

new DataTable('#urlcnt', {
	data: urlFrequency,
	columns: [
		{ title: "Hits" },
		{ title: "TX" },
		{ title: "Method" },
		{ title: "Protocol" },
		{ title: "URL" }
	],
	order: [[ 0, "desc" ]],
	lengthMenu: [ 10, 20, 30, 40, 50, 100, 150, -1 ],
	columnDefs: [ { targets: 1, className: 'dt-body-right' } ]
} );

// Apache ECharts
var dom1 = document.getElementById("containerYear");
var dom2 = document.getElementById("containerYearMonth");
var dom3 = document.getElementById("containerYearWeek");
var myChart = [ echarts.init(dom1), echarts.init(dom2), echarts.init(dom3) ];

d(0);

</script>

</html>


EOF


