#!/usr/bin/perl -w
# Change Commerzbank telephone number from short form (5-digit) to long form
# Elmar Klausmeier, 15-Nov-2010

my $i=0;
my ($catCoba, $catMC, $catHVB, $catcomdirect, $catDB,$catKfW) = (0,0,0,0,0,0);

while (<>) {
	next if (/^PRODID:\-/ || /^UID:/);
	#if (/^UID:/) { ++$i; print "UID:$i\n"; next; }
	$catCoba = 1 if (/^CATEGORIES:Commerzbank/);
	$catMC = 1 if (/^CATEGORIES:Mummert/);
	$catHVB = 1 if (/^CATEGORIES:HVB/);
	$catcomdirect = 1 if (/^CATEGORIES:comdirect/);
	$catDB = 1 if (/^CATEGORIES:Deutsche Bank/);
	$catKfW = 1 if (/^ORG:KfW/);

	($catCoba, $catMC, $catHVB, $catcomdirect, $catDB,$catKfW) = (0,0,0,0,0,0)
		if (/^END:VCARD/);

	if ($catCoba == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{5}\r)/${1}:+49 69-136-${3}/;
	} elsif ($catMC == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{4}\r)/${1}:+49 40-22703-${3}/;
	} elsif ($catHVB == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{5}\r)/${1}:+49 89-378-${3}/;
	} elsif ($catcomdirect == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{4}\r)/${1}:+49 4106-704-${3}/;
	} elsif ($catDB == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{5}\r)/${1}:+49 69-910-${3}/;
	} elsif ($catKfW == 1) {
		s/(TEL;TYPE=work)(|,pref):(\d{4,6}\r)/${1}:+49 69-7431-${3}/;
	}

	# Mobilfunknummern mit internationaler Vorwahl versehen
	s/(TEL;TYPE=cell)(|,pref):01(5|6|7)/${1}:+49 1${3}/;

	# Frankfurter, Hamburger oder Münchener Nummern mit internationaler Vorwahl versehen
	s/(TEL;TYPE=)(home|fax|work|cell|x-other)(|,pref):0(2|3|4|5|6|7|8|9)/${1}${2}:+49 ${4}/;

	s/^X-:www\./URL:www\./;
	s/^X-:/NICKNAME:/;
	# J-Pilot export bug
	s/^ADDR/ADR/;

	print;
}

